=== davidoram/go-schema-lang/schemas/campaign.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Campaign",
    "type": "object",
    "required": ["id", "name", "active", "start_date", "rewards"],
    "properties": {
      "id": { "type": "string" },
      "name": { "type": "string" },
      "description": { "type": "string" },
      "active": { "type": "boolean" },
      "start_date": { "type": "string", "format": "date-time" },
      "end_date": { "type": "string", "format": "date-time" },
      "triggers": {
        "type": "array",
        "items": {
          "oneOf": [
            { "$ref": "simple_condition.json#" },
            { "$ref": "aggregate_condition.json#" }
          ]
        }
      },
      "conditions": {
        "type": "array",
        "items": {
          "oneOf": [
            { "$ref": "simple_condition.json#" },
            { "$ref": "aggregate_condition.json#" }
          ]
        }
      },
      "rewards": {
        "type": "array",
        "items": {
          "type": "object",
          "required": ["type", "value", "currency"],
          "properties": {
            "kind": { "type": "string" },
            "value": { "type": "number" },
            "currency": { "type": "string" }
          }
        }
      }
    },
    "additionalProperties": false
  }

=== davidoram/go-schema-lang/campaigns/sample_1.json
{
    "id": "campaign-001",
    "name": "Mobile app download campaign",
    "description": "A campaign to promote mobile app downloads.",
    "active": true,
    "start_date": "2023-03-15T00:00:00Z",
    "end_date": "2023-04-15T00:00:00Z",
    "triggers": [
      {
        "type": "simple_condition",
        "clauses": [
          {
            "source": "triggerEvent",
            "operator": "equals",
            "parameters": [
              "mobile.app.download",
              { "jsonPath": "$.event_taxonomy" }
            ]
          }
        ]
      }
    ],
    "conditions": [
      {
        "type": "aggregate_condition",
        "parameters": {
          "filter": [
            {
              "type": "simple_condition",
              "clauses": [
                {
                  "source": "eventHistory",
                  "operator": "equals",
                  "parameters": [
                    { "jsonPath": "$.kind" },
                    "credit"
                  ]
                },
                {
                  "source": "eventHistory",
                  "operator": "equals",
                  "parameters": [
                    { "jsonPath": "$.business_data['campaign_id']" },
                    "campaign-001"
                  ]
                }
              ]
            }
          ],
          "group_by": [],
          "conditions": [
            {
              "type": "simple_condition",
              "clauses": [
                {
                  "source": "eventHistory",
                  "operator": "equals",
                  "parameters": [
                    { "jsonPath": "$.count" },
                    0
                  ]
                }
              ]
            }
          ]
        }
      }
    ],
    "rewards": [
      {
        "type": "discount",
        "value": 10.5,
        "currency": "USD",
        "business_data": {
          "campaign_id": "campaign-001"
        }
      }
    ]
  }
